spring:
  profiles:
    active: dev


# Server settings
server:
  address: localhost
  port: 8081
  sessionTimeout: 3000

# Mmultipart settings
multipart:
  maxFileSize: 10Mb
  maxRequestSize: 10Mb


# File upload settings
file-upload:
  root-path: /home/seeyou/upload/
  visa-path: visa/

---

# Spring settings
spring:
  profiles: dev

  thymeleaf:
    suffix: .html
    mode: HTML5
    cache: false
    encoding: UTF-8

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://101.201.66.95:3306/winery?characterEncoding=UTF-8&autoReconnect=true&failOverReadOnly=false&maxReconnects=10&testOnBorrow=true&validationQuery=select 1
#    username: winery
#    password: winery123
#    url: jdbc:mysql://139.219.13.249:3306/winery?characterEncoding=UTF-8&autoReconnect=true&failOverReadOnly=false&maxReconnects=10&testOnBorrow=true&useSSL=false&validationQuery=select 1
#    username: root
#    password: Wise_@123456

    url: jdbc:mysql://39.106.184.86:3306/winery?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 3Y4T8S#dl$d12*$@wyy
    # 可指定数据源，如果不指定则使用默认的数据源（com.zaxxer.hikari.HikariDataSource）
    type: com.alibaba.druid.pool.DruidDataSource
    # druid连接池的配置信息
    # 初始化大小，最小，最大
    initialSize: 3
    minIdle: 5
    maxActive: 20
    # 配置获取连接等待超时的时间

    maxWait: 30000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testOnBorrow: false
    testOnReturn: false
    testWhileIdle: true
    # 打开PSCache，并且指定每个连接上PSCache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=10000


  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none


---

# Spring settings
spring:
  profiles: work

  thymeleaf:
    suffix: .html
    mode: HTML5
    cache: false
    encoding: UTF-8

  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://42.159.9.46:3306/winery?characterEncoding=UTF-8&autoReconnect=true&failOverReadOnly=false&maxReconnects=10&useSSL=false
    username: root
    password: wise_@123
#    url: jdbc:mysql://127.0.0.1:3306/winery?characterEncoding=UTF-8&autoReconnect=true&failOverReadOnly=false&maxReconnects=10&testOnBorrow=true&validationQuery=select 1
#    username: root
#    password: root
#    url: jdbc:mysql://139.219.13.249:3306/winery?characterEncoding=UTF-8&autoReconnect=true&failOverReadOnly=false&maxReconnects=10&testOnBorrow=true&useSSL=false&validationQuery=select 1
#    username: root
#    password: Wise_@123456
    initialSize: 0
    maxActive: 4
    maxIdle: 4
    minIdle: 4
    testOnBorrow: false
    testOnReturn: false
    testWhileIdle: true
    maxWait: 60000

  jpa:
    show-sql: true
#    hibernate:
#      ddl-auto: update

  mvc:
    formcontent:
      putfilter:
        enabled: false

mybatis:
  # MyBatis实体类所在的包路径
  type-aliases-package: com.changfa.frame.model.**
  # 配置映射mapper.xml所在路径
  mapper-locations: classpath*:/mybatis/**/*Mapper.xml
  # mybatis的配置文件路径
  config-location: classpath*:/mybatis/mybatis-config.xml

# 分页插件配置
pagehelper:
  helperDialect: mysql
  reasonable: true
  support-methods-arguments: true
  offset-as-page-num: true
  row-bounds-with-count: true
  page-size-zero: true
  params: pageNumber=start;pageSize=limit;count=countSql

logging:
  config: classpath:logback-spring.xml