# ***************** server配置 开始 ******************************** #
server:
  address: localhost
  port: 8080
  sessionTimeout: 3000
  tomcat:
    uri-encoding: UTF-8

# ***************** 属性文件配置 开始 ******************************** #
system:
  properties:
    files: application-service.properties

# ***************** spring配置 开始 ******************************** #
spring:
  profiles:
    active: service
  # ***************** 数据源配置 开始 ******************************** #
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://39.106.184.86:3306/winery?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: winery
    password: winery123@Tw123876
    type: com.alibaba.druid.pool.DruidDataSource
    initialSize: 3
    minIdle: 5
    maxActive: 20
    maxWait: 30000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testOnBorrow: false
    testOnReturn: false
    testWhileIdle: true
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    filters: stat,wall
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=10000
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    database: mysql
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect

  #***************** Redis配置 开始 ********************************#
  redis:
    host: 127.0.0.1
    port: 6379
    password: root
    timeout: 3000
    database: 0
    jedis:
      pool:
        max-idle: 200
        min-idle: 20
        max-active: 50
        max-wait: 1000

  #***************** 文件上传配置 开始 ********************************#
  servlet:
    multipart:
      max-file-size: 512MB
      max-request-size: 512MB
      enabled: true

  #***************** Http请求编码配置 开始 ********************************#
  http:
    encoding:
      enabled: true
      force: true
      charset: utf-8

# ***************** mybatis配置 开始 ******************************** #
mybatis:
  type-aliases-package: com.changfa.frame.model.**
  mapper-locations: classpath:/mybatis/**/*Mapper.xml
  config-location: classpath:/mybatis/mybatis-config.xml
pagehelper:
  helperDialect: mysql
  reasonable: true
  support-methods-arguments: true
  offset-as-page-num: true
  row-bounds-with-count: true
  page-size-zero: true
  params: pageNumber=start;pageSize=limit;count=countSql

# ***************** logback配置 开始 ******************************** #
logging:
  config: classpath:logback-spring.xml
